// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm4kM7c0a7efMrVRUJzmwW4xi1aX0eEBM',
    appId: '1:82362499274:web:76d865bec86a7e61cf3433',
    messagingSenderId: '82362499274',
    projectId: 'petaholic-4b075',
    authDomain: 'petaholic-4b075.firebaseapp.com',
    storageBucket: 'petaholic-4b075.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr4T9K8opMi5tT0_FSYo9EAWgf5YF4RKU',
    appId: '1:82362499274:android:f7fdb507df4d3057cf3433',
    messagingSenderId: '82362499274',
    projectId: 'petaholic-4b075',
    storageBucket: 'petaholic-4b075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtOJ32b9ZO4kne-ufAyNWdCk0rndkO3Nc',
    appId: '1:82362499274:ios:b6985b0793f9c81dcf3433',
    messagingSenderId: '82362499274',
    projectId: 'petaholic-4b075',
    storageBucket: 'petaholic-4b075.appspot.com',
    iosBundleId: 'com.example.petaholic',
  );
}
